name: Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Core checks (${{ matrix.architecture }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            environment: linux
          - architecture: arm64
            environment: arm
    runs-on:
      - codebuild-fan-curve-release-runner-${{ github.run_id }}-${{ github.run_attempt }}
      - image:custom-${{ matrix.environment }}-swift:6.1-jammy
      - instance-size:small
      - buildspec-override:true
      - core-${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: swift --version
      - run: swift run FanCurveCheck

  app-actions:
    name: App user actions
    runs-on: ${{ fromJSON(vars.MACOS_RUNNER || '"macos-15"') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: swift build -Xswiftc -warnings-as-errors
      - run: swift build --target FanCurveAppCheck -Xswiftc -strict-concurrency=complete -Xswiftc -warnings-as-errors
      - run: swift run FanCurveAppCheck
      - run: swift build -c release --triple x86_64-apple-macosx13.0
      - if: ${{ runner.environment == 'github-hosted' }}
        run: sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      - run: arch -x86_64 .build/out/Products/Release/FanCurveCheck
      - run: arch -x86_64 .build/out/Products/Release/FanCurveAppCheck
